<?php


use Drupal\Component\Utility\Unicode;
use Drupal\Core\Block\BlockPluginInterface;
/**
 * Implements hook_block_view_alter().
 */
function block_example_block_view_alter(array &$build, BlockPluginInterface $block) {

  var_dump('block hook'); die;

  $definition = $block->getPluginDefinition();

  if ((!empty($build['#configuration']['label']) && stristr($build['#configuration']['label'], 'uppercase'))
    || (!empty($definition['subject']) && stristr($definition['subject'], 'uppercase'))) {

    $build['#configuration']['label'] = Unicode::strtoupper($build['#configuration']['label']);

  }

}